DELETE FROM likes;
DELETE FROM film_genre;
DELETE FROM films;
DELETE FROM users;
DELETE FROM genres;
DELETE FROM mpa_rating;

-- Вставляем MPA и жанры (без KEY!)
INSERT INTO mpa_rating (rating_id, name) VALUES
  (1, 'G'),
  (2, 'PG'),
  (3, 'PG-13'),
  (4, 'R'),
  (5, 'NC-17');

INSERT INTO genres (genre_id, name) VALUES
  (1, 'Комедия'),
  (2, 'Драма'),
  (3, 'Мультфильм'),
  (4, 'Триллер'),
  (5, 'Документальный'),
  (6, 'Боевик');

-- Фильмы с явными ID (требует GENERATED BY DEFAULT AS IDENTITY)
INSERT INTO films (film_id, name, description, releaseDate, duration, mpa_id) VALUES
  (1, 'Фильм А', 'Описание фильма А', '2000-01-01 00:00:00', 100, 1),
  (2, 'Фильм Б', 'Описание фильма Б', '2001-01-01 00:00:00', 110, 2);

-- Связи
INSERT INTO film_genre (film_id, genre_id) VALUES
  (1, 1),
  (2, 2),
  (2, 4);

-- Пользователи с явными ID
INSERT INTO users (user_id, email, login, name, birthday) VALUES
  (1, 'user1@test.com', 'user1', 'Пользователь 1', '1990-01-01'),
  (2, 'user2@test.com', 'user2', 'Пользователь 2', '1995-01-01');

-- Лайки
INSERT INTO likes (user_id, film_id) VALUES
  (1, 1),
  (2, 1),
  (1, 2);